export interface MeetEvent {
  id: string;
  title: string;
  date: string;
  time: string;
  location: string;
  address: string;
  latitude: number;
  longitude: number;
  price: string;
  description: string;
  category: string;
  imageUrl: string;
  program: string[];
  organizerId: string;
}

export interface Organizer {
  id: string;
  name: string;
  bio: string;
  followers: number;
  rating: number;
  avatarInitial: string;
  avatarColor: string;
}

export const ORGANIZERS: Organizer[] = [
  {
    id: 'org1',
    name: 'Алексей Новиков',
    bio: 'Организую лучшие техно-вечеринки в Мск 🎧',
    followers: 12400,
    rating: 4.9,
    avatarInitial: 'А',
    avatarColor: '#0f766e',
  },
  {
    id: 'org2',
    name: 'Мария Соколова',
    bio: 'Культурные события, выставки и арт-пространства 🎨',
    followers: 8750,
    rating: 4.8,
    avatarInitial: 'М',
    avatarColor: '#7c3aed',
  },
  {
    id: 'org3',
    name: 'Дмитрий Волков',
    bio: 'Стендап-продюсер. Смех — наш бизнес 😂',
    followers: 34200,
    rating: 4.7,
    avatarInitial: 'Д',
    avatarColor: '#b45309',
  },
  {
    id: 'org4',
    name: 'Елена Захарова',
    bio: 'IT-конференции и tech-митапы Москвы 💻',
    followers: 19800,
    rating: 4.95,
    avatarInitial: 'Е',
    avatarColor: '#0369a1',
  },
];

export const MOSCOW_EVENTS: MeetEvent[] = [
  {
    id: '1',
    title: 'VK Fest 2024',
    date: 'Суббота, 20 Июл',
    time: '12:00',
    location: 'Лужники',
    address: 'Стадион Лужники, Москва',
    latitude: 55.7151,
    longitude: 37.5539,
    price: '2 500 ₽',
    description:
      'Главный музыкальный фестиваль лета от ВКонтакте. Три дня живой музыки, фудкорты, творческие зоны и масса активностей для всей семьи. Выступят топовые артисты Russia и зарубежные хедлайнеры.',
    category: 'Музыка',
    imageUrl:
      'https://picsum.photos/id/111/800/1200',
    organizerId: 'org1',
    program: [
      '12:00 — Открытие и регистрация',
      '14:00 — Первый блок выступлений',
      '17:00 — Хедлайнер основной сцены',
      '21:00 — Ночной блок и afterparty',
    ],
  },
  {
    id: '2',
    title: 'Артефакт: Выставка ИИ-искусства',
    date: 'Воскресенье, 21 Июл',
    time: '11:00',
    location: 'Гараж',
    address: 'Музей Гараж, Парк Горького, Москва',
    latitude: 55.7298,
    longitude: 37.6018,
    price: '800 ₽',
    description:
      'Интерактивная выставка работ, созданных искусственным интеллектом в соавторстве с художниками. Живопись, скульптура, видеоарт и звуковые инсталляции, которые переосмысляют творческий процесс.',
    category: 'Искусство',
    imageUrl:
      'https://picsum.photos/id/112/800/1200',
    organizerId: 'org2',
    program: [
      '11:00 — Открытие галерей',
      '13:00 — Лекция куратора выставки',
      '15:00 — Воркшоп "Создай свой ИИ-арт"',
      '18:00 — Закрытие экспозиции',
    ],
  },
  {
    id: '3',
    title: 'Дизайн-выходные на Флаконе',
    date: 'Суббота, 03 Авг',
    time: '10:00',
    location: 'Дизайн-завод Флакон',
    address: 'Флакон, ул. Большая Новодмитровская, 36',
    latitude: 55.8017,
    longitude: 37.5878,
    price: 'Бесплатно',
    description:
      'Два дня погружения в мир дизайна, типографики и брендинга. Мастер-классы, лекции от дизайнеров ведущих студий России, маркет независимых брендов и ярмарка принтов.',
    category: 'Дизайн',
    imageUrl:
      'https://picsum.photos/id/113/800/1200',
    organizerId: 'org2',
    program: [
      '10:00 — Открытие маркета',
      '12:00 — Лекция "Тренды дизайна 2024"',
      '14:00 — Мастер-класс по каллиграфии',
      '17:00 — Portfolio review с арт-директорами',
    ],
  },
  {
    id: '4',
    title: 'TEDxMoscow 2024',
    date: 'Пятница, 09 Авг',
    time: '18:00',
    location: 'Сколково',
    address: 'Инновационный центр Сколково, Москва',
    latitude: 55.7,
    longitude: 37.36,
    price: '3 000 ₽',
    description:
      'Ежегодная конференция TED в Москве. Восемь спикеров с идеями, достойными распространения — от нейронаук до устойчивого развития городов. Живое общение, нетворкинг и вдохновение.',
    category: 'Конференция',
    imageUrl:
      'https://picsum.photos/id/114/800/1200',
    organizerId: 'org4',
    program: [
      '18:00 — Регистрация и welcome drinks',
      '19:00 — Открытие и первый блок докладов',
      '20:30 — Нетворкинг пауза',
      '21:00 — Финальный блок и закрытие',
    ],
  },
  {
    id: '5',
    title: 'Джазовые вечера в Парке Горького',
    date: 'Четверг, 15 Авг',
    time: '20:00',
    location: 'Парк Горького',
    address: 'Центральный Парк Культуры и Отдыха, Москва',
    latitude: 55.7287,
    longitude: 37.6012,
    price: 'Бесплатно',
    description:
      'Еженедельные джазовые концерты под открытым небом в самом сердце Москвы. Профессиональные музыканты, мягкий вечерний воздух и атмосфера лёгкости — лучший формат летнего вечера.',
    category: 'Музыка',
    imageUrl:
      'https://picsum.photos/id/115/800/1200',
    organizerId: 'org1',
    program: [
      '20:00 — Открытие и разминочный сет',
      '20:30 — Выступление Moscow Jazz Quartet',
      '21:30 — Guestset: DJ Soul Collective',
      '23:00 — Завершение',
    ],
  },
  {
    id: '6',
    title: 'Сид',
    date: '29–30 мая',
    time: '19:00',
    location: 'Театр драмы',
    address: 'ул. Октябрьская, 78',
    latitude: 55.78,
    longitude: 37.61,
    price: '16+',
    description: 'Сильная драма о любви, долге и чести. Классическая постановка в современном прочтении, которая не оставит равнодушным ни одного зрителя.',
    category: 'Спектакль',
    imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800',
    organizerId: 'org2',
    program: ['18:30 — Сбор гостей', '19:00 — Начало спектакля', '20:30 — Антракт', '22:00 — Финал'],
  },
  {
    id: '7',
    title: 'Ромео и Джульетта. Пилигримы Вероны',
    date: '03–24 апреля',
    time: '18:00',
    location: 'Театр «Скарабей»',
    address: 'ул. Коммуны, 129',
    latitude: 55.75,
    longitude: 37.58,
    price: '16+',
    description: 'Вечная история любви в необычном пространстве театра «Скарабей». Пилигримы, Верона и судьба, предначертанная звездами.',
    category: 'Спектакль',
    imageUrl: 'https://images.unsplash.com/photo-1503095396549-807a8bc3667c?w=800',
    organizerId: 'org2',
    program: ['17:30 — Открытие дверей', '18:00 — Начало действия', '20:00 — Обсуждение с актерами'],
  },
  {
    id: '8',
    title: 'Пер Гюнт',
    date: '15 июня',
    time: '18:30',
    location: 'Оперный театр',
    address: 'площадь Ярославского, 1',
    latitude: 55.76,
    longitude: 37.62,
    price: '18+',
    description: 'Масштабная постановка по пьесе Генрика Ибсена. Путешествие героя сквозь время и пространство в поисках самого себя.',
    category: 'Спектакль',
    imageUrl: 'https://images.unsplash.com/photo-1514302240736-b1fee5985889?w=800',
    organizerId: 'org2',
    program: ['18:00 — Welcome drink', '18:30 — Пролог', '21:00 — Финальная сцена'],
  },
  {
    id: '9',
    title: 'Кирилл Мазур',
    date: '06 июня',
    time: '19:00',
    location: 'Конгресс-холл',
    address: 'ул. Труда, 153',
    latitude: 55.74,
    longitude: 37.53,
    price: '18+',
    description: 'Сольный стендап-концерт одного из самых ярких комиков нового поколения. Острый юмор, личные истории и невероятная харизма.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1585699324551-f6c309eedee6?w=800',
    organizerId: 'org3',
    program: ['18:30 — Вход', '19:00 — Разогрев', '19:20 — Кирилл Мазур', '21:00 — Фотосессия'],
  },
  {
    id: '10',
    title: 'Стендап-советы',
    date: '04–18 апреля',
    time: '20:00',
    location: 'Стендап-клуб',
    address: 'ул. Академика Королева, 3',
    latitude: 55.82,
    longitude: 37.6,
    price: '18+',
    description: 'Комики дают советы зрителям в формате импровизации. Смешно, местами нелепо, но всегда жизненно.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800',
    organizerId: 'org3',
    program: ['20:00 — Начало шоу', '21:30 — Завершение'],
  },
  {
    id: '11',
    title: 'Опытный микрофон',
    date: '02–11 апреля',
    time: '19:30',
    location: 'Стендап-клуб',
    address: 'ул. Академика Королева, 3',
    latitude: 55.821,
    longitude: 37.601,
    price: '18+',
    description: 'Проверка материала от опытных комиков. Только лучшие шутки, которые скоро попадут в ТВ-проекты.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1549490349-8643362247b5?w=800',
    organizerId: 'org3',
    program: ['19:30 — Старт', '21:00 — Конец'],
  },
  {
    id: '12',
    title: 'Никита Шевчук',
    date: '15 ноября',
    time: '18:00',
    location: 'Конгресс-холл',
    address: 'ул. Труда, 153',
    latitude: 55.739,
    longitude: 37.531,
    price: '18+',
    description: 'Большой сольный концерт самого стильного комика. Тонкие наблюдения и интеллигентный юмор.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1481162853351-d410ae266070?w=800',
    organizerId: 'org3',
    program: ['18:00 — Начало'],
  },
  {
    id: '13',
    title: 'Ольга Малащенко',
    date: '18 апреля',
    time: '19:00',
    location: 'Конгресс-холл',
    address: 'ул. Труда, 153',
    latitude: 55.741,
    longitude: 37.529,
    price: '18+',
    description: 'Дерзкий и откровенный стендап от Ольги Малащенко. Женский взгляд на мужские проблемы и наоборот.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1478737270239-2fccd2c7fd14?w=800',
    organizerId: 'org3',
    program: ['19:00 — Начало концерта'],
  },
  {
    id: '14',
    title: 'Иван Абрамов',
    date: '08 ноября',
    time: '19:00',
    location: 'Таганай',
    address: 'ул. Труда, 181',
    latitude: 55.735,
    longitude: 37.545,
    price: '18+',
    description: 'Музыкальный стендап от мастера перевоплощений. Инструментальное сопровождение и острые шутки.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800',
    organizerId: 'org3',
    program: ['19:00 — Стендап-шоу'],
  },
  {
    id: '15',
    title: 'Виктория Складчикова',
    date: '11 апреля',
    time: '19:00',
    location: 'Таганай',
    address: 'ул. Труда, 181',
    latitude: 55.736,
    longitude: 37.546,
    price: '18+',
    description: 'Простота, искренность и невероятный юмор Виктории Складчиковой в большом сольном шоу.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800',
    organizerId: 'org3',
    program: ['19:00 — Начало'],
  },
  {
    id: '16',
    title: 'Женский форум',
    date: '23 мая',
    time: '19:00',
    location: 'Таганай',
    address: 'ул. Труда, 181',
    latitude: 55.734,
    longitude: 37.544,
    price: '18+',
    description: 'Популярное шоу в живом формате. Комики и гости обсуждают самые странные вопросы с женских форумов.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb28f74b671?w=800',
    organizerId: 'org3',
    program: ['19:00 — Паблик-ток'],
  },
  {
    id: '17',
    title: 'Битва комиков',
    date: '03–17 апреля',
    time: '21:00',
    location: 'Стендап-клуб',
    address: 'ул. Академика Королева, 3',
    latitude: 55.822,
    longitude: 37.599,
    price: '18+',
    description: 'Турнир комиков на вылет. Зрители решают, кто пройдет в финал и заберет денежный приз.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1502444330042-d1a1ddf9bb5b?w=800',
    organizerId: 'org3',
    program: ['21:00 — Первый раунд', '22:30 — Оглашение результатов'],
  },
  {
    id: '18',
    title: 'Артур Шамгунов',
    date: '05 апреля',
    time: '17:00',
    location: 'Стендап-клуб',
    address: 'ул. Академика Королева, 3',
    latitude: 55.819,
    longitude: 37.602,
    price: '18+',
    description: 'Философский стендап от Артура Шамгунова. О жизни, татарском воспитании и казанских буднях.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800',
    organizerId: 'org3',
    program: ['17:00 — Начало'],
  },
  {
    id: '19',
    title: 'Большой стендап',
    date: 'апрель–май',
    time: '20:00',
    location: 'Стендап-клуб',
    address: 'ул. Академика Королева, 3',
    latitude: 55.82,
    longitude: 37.61,
    price: '18+',
    description: 'Сборный концерт лучших комиков страны. Каждую неделю новые лица и проверенные шутки.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1551632432-c735e8299c52?w=800',
    organizerId: 'org3',
    program: ['20:00 — Начало марафона'],
  },
  {
    id: '20',
    title: 'Грязный стендап',
    date: '04–18 апреля',
    time: '23:00',
    location: 'Стендап-клуб',
    address: 'ул. Академика Королева, 3',
    latitude: 55.82,
    longitude: 37.598,
    price: '18+',
    description: 'Юмор без цензуры и границ. Только для взрослых и людей с крепкими нервами.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800',
    organizerId: 'org3',
    program: ['23:00 — Ночное шоу'],
  },
  {
    id: '21',
    title: 'Андрей Бебуришвили',
    date: '26 апреля',
    time: '19:00',
    location: 'Таганай',
    address: 'ул. Труда, 181',
    latitude: 55.733,
    longitude: 37.547,
    price: '18+',
    description: 'Пафос, самоирония и великолепный юмор Андрея Бебуришвили в большом сольном концерте.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1525206121484-9005fbcba71f?w=800',
    organizerId: 'org3',
    program: ['19:00 — Начало шоу'],
  },
  {
    id: '22',
    title: 'Артем Винокур',
    date: '09 апреля',
    time: '20:00',
    location: 'Конгресс-холл',
    address: 'ул. Труда, 153',
    latitude: 55.742,
    longitude: 37.532,
    price: '18+',
    description: 'Артем Винокур с новой программой. Энергичный стендап о жизни в столице и не только.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800',
    organizerId: 'org3',
    program: ['20:00 — Начало'],
  },
  {
    id: '23',
    title: 'Большой открытый микрофон',
    date: 'апрель',
    time: '18:00',
    location: 'Конгресс-холл',
    address: 'ул. Труда, 153',
    latitude: 55.74,
    longitude: 37.53,
    price: '18+',
    description: 'Десятки комиков, сотни шуток. Кто-то станет звездой, а кто-то просто уйдет под стук сверчков.',
    category: 'Стендап',
    imageUrl: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800',
    organizerId: 'org3',
    program: ['18:00 — Старт микрофона'],
  },
];
